name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore bbt.sln

      - name: Build
        run: dotnet build bbt.sln -c Release --no-restore

      - name: Test
        run: dotnet test bbt.sln -c Release --no-build

      - name: Pack (smoke)
        run: dotnet pack src/Bbt/Bbt.csproj -c Release --no-build -o artifacts
